name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2
  PIP_PROGRESS_BAR: 'off'

defaults:
  run:
    shell: bash -c "exec $CONDA_PREFIX/bin/bash -elo pipefail {0}"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3']
        x: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    env:
      PYTEST_ADDOPTS: --cov --color=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install System Dependencies
        uses: mamba-org/setup-micromamba@v3
        with:
          cache-environment: true
          post-cleanup: 'all'
          environment-name: cylc-uiserver
          create-args: >-
            python=${{ matrix.python-version }}
            pip
            bash
            coreutils

      - name: install cylc-flow
        uses: cylc/release-actions/install-cylc-components@v1
        with:
          cylc_flow: true
          cylc_flow_opts: ''
          cylc_flow_tag: '8.6.x'
          # Required for coverage collection
          editable_installations: true

      - name: install cylc-uiserver
        run: |
          pip install -e .[all]

      - name: Test
        run: pytest

      - name: Cylc Review tests
        id: review_tests
        run: |
          CONF_PATH="$HOME/.cylc/flow/8"
          mkdir -p "$CONF_PATH"
          touch "$CONF_PATH/global.cylc"
          ln -s "$CONF_PATH/global.cylc" "$CONF_PATH/global-tests.cylc"

          cat >> "$CONF_PATH/global.cylc" <<__HERE__
          [platforms]
            [[_local_background_shared_tcp]]
              hosts = localhost
              install target = localhost
              ssh command = ssh -oBatchMode=yes -oConnectTimeout=8 -oStrictHostKeyChecking=no
          __HERE__

          # Check that Cylc Review is installed!
          # (We're only interested if it emits an error):
          cylc review --help > /dev/null || exit 1

          # Run tests on Cylc Review
          export CYLC_COVERAGE=1
          export CYLC_COVERAGE_BASE=$PWD
          ./etc/bin/run-functional-tests

      - name: Coverage report
        run: |
          set -x
          coverage xml --debug=pathmap,trace
          coverage report
